// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alg1_batch_cpp
List alg1_batch_cpp(const arma::mat& inv_dotZtZ, const arma::vec& theta_hat, double sigma2_hat, int N_old, int n_old, const arma::mat& x_mat, const arma::ivec& time_vec, const arma::vec& y_vec, const arma::ivec& unit_lens, int T_support, int baseline_time);
RcppExport SEXP _otwfe_alg1_batch_cpp(SEXP inv_dotZtZSEXP, SEXP theta_hatSEXP, SEXP sigma2_hatSEXP, SEXP N_oldSEXP, SEXP n_oldSEXP, SEXP x_matSEXP, SEXP time_vecSEXP, SEXP y_vecSEXP, SEXP unit_lensSEXP, SEXP T_supportSEXP, SEXP baseline_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type inv_dotZtZ(inv_dotZtZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_hat(theta_hatSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_hat(sigma2_hatSEXP);
    Rcpp::traits::input_parameter< int >::type N_old(N_oldSEXP);
    Rcpp::traits::input_parameter< int >::type n_old(n_oldSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type time_vec(time_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type unit_lens(unit_lensSEXP);
    Rcpp::traits::input_parameter< int >::type T_support(T_supportSEXP);
    Rcpp::traits::input_parameter< int >::type baseline_time(baseline_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(alg1_batch_cpp(inv_dotZtZ, theta_hat, sigma2_hat, N_old, n_old, x_mat, time_vec, y_vec, unit_lens, T_support, baseline_time));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_otwfe_alg1_batch_cpp", (DL_FUNC) &_otwfe_alg1_batch_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_otwfe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
