# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Algorithm 1 배치: 새 unit M개를 한 번에 처리
#'
#' @param inv_dotZtZ  p × p, 업데이트 전 (\dot{Z}'\dot{Z})^{-1}
#' @param theta_hat   p, 업데이트 전 계수 벡터
#' @param sigma2_hat  업데이트 전 sigma^2
#' @param N_old       업데이트 전 unit 수
#' @param n_old       업데이트 전 총 관측치 수
#' @param x_mat       n_stream × k, 새 unit들의 공변량 (unit 순서대로 연결)
#' @param time_vec    n_stream, 재인덱싱된 calendar time (1..T_support)
#' @param y_vec       n_stream, 종속변수
#' @param unit_lens   M, 각 unit의 관측치 수 (합 = n_stream)
#' @param T_support   현재 calendar time support 크기
#' @param baseline_time 제거한 기준 time dummy
#' @return list: inv_dotZtZ, theta_hat, sigma2_hat, M_ss_add,
#'               A_N_add, B_N_add, N_add, n_add
alg1_batch_cpp <- function(inv_dotZtZ, theta_hat, sigma2_hat, N_old, n_old, x_mat, time_vec, y_vec, unit_lens, T_support, baseline_time) {
    .Call(`_otwfe_alg1_batch_cpp`, inv_dotZtZ, theta_hat, sigma2_hat, N_old, n_old, x_mat, time_vec, y_vec, unit_lens, T_support, baseline_time)
}

